export { default as TeacherProfile } from "./TeacherProfile";
export { default as TeacherSettings } from "./TeacherSettings";
export { default as TeacherHome } from "./TeacherHome";
export { default as Students } from "./Students";
export { default as Quizzes } from "./Quizzes";
export { default as Assignments } from "./Assignments";
export { default as StudentsExams } from "./StudentsExams";
export { default as Grading } from "./Grading";
export { default as AnnouncementsPage } from "./AnnouncementsPage";
