export { default as StudentProfile } from "./StudentProfile";
export { default as ChangePassword } from "./ChangePassword";
export { default as Courses } from "./Courses";
export { default as CourseWork } from "./CourseWork";
export { default as Progress } from "./Progress";
export { default as Exams } from "./Exams";
export { default as Results } from "./Results";
export { default as Contact } from "./Contact";
export { default as Announcements } from "./Announcements";
